### PR TITLE
Fixes #181 | Count sync (de)registration

### LINKED ISSUE #181: Count sync (de)registration
We should collect how many (de)registration are performed by sync. If it's more than 0 then probably something went wrong.

### PR DESCRIPTION
**Pull request by tomez**

### CODE REVIEW

File: sync/sync.go [hunk 1]
```diff
@@ -157,7 +165,9 @@ func (s *Sync) registerAppTasksNotFoundInConsul(marathonApps []*apps.App, servic
 					err := s.serviceRegistry.Register(&task, app)
 					if err != nil {
 						log.WithError(err).WithField("Id", task.ID).Error("Can't register task")
+						continue
```
Comment (kamilchm) [inline sync/sync.go]: I would prefer incrementing counter in else condition

Comment (tomez) [inline sync/sync.go]: Fixed
